version: '3.8'
services:
  api:
    image: yuriydetsyk/gamers:${DEPLOY_TAG:-latest}
    container_name: gamers-api-${GAMERS_ENV:?}
    restart: unless-stopped
    build:
      context: ./
      target: production
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - GAMERS_DB_USERNAME=${GAMERS_DB_USERNAME:?}
      - GAMERS_DB_PASSWORD=${GAMERS_DB_PASSWORD:?}
      - GAMERS_DB_PORT=${GAMERS_DB_PORT:?}
      - GAMERS_PORT=${GAMERS_PORT:?}
      - GAMERS_ENV=${GAMERS_ENV:?}
      - GAMERS_SESSION_SECRET=${GAMERS_SESSION_SECRET:?}
      - GAMERS_AWS_ACCESS_KEY_ID=${GAMERS_AWS_ACCESS_KEY_ID:?}
      - GAMERS_AWS_SECRET_ACCESS_KEY=${GAMERS_AWS_SECRET_ACCESS_KEY:?}
      - GAMERS_AWS_IMG_BUCKET=${GAMERS_AWS_IMG_BUCKET:?}
    ports:
      - ${GAMERS_PORT:-4800}:4800
    networks:
      - gamers_network
    depends_on:
      database:
        condition: service_healthy
    profiles: ["production"]

networks:
  gamers_network:
    name: gamers_network_${GAMERS_ENV:-dev}
